### ISSUE TITLE
 segment_anything module

### ISSUE THREAD

**Issue by mowangmodi** [cnhaox/NeRF-HuGS#1]
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
from segment_anything.utils.amg import calculate_stability_score

It seems that there is no segment-anything module provided:ModuleNotFoundError: No module named 'segment_anything

**Comment by mowangmodi** [comment]
I am training the photoourism dataset, and the generate-static_mask.py prompt shows that there is no segmentation module

**Comment by cnhaox** [comment]
> I am training the photoourism dataset, and the generate-static_mask.py prompt shows that there is no segmentation module

Hi there! This looks like the segment-anything module is not installed in your conda environment. I've just updated the [README.md](https://github.com/cnhaox/NeRF-HuGS/blob/master/README.md) and [requirements_torch.txt](https://github.com/cnhaox/NeRF-HuGS/blob/master/requirements_torch.txt), and you can follow them to prepare the environment.
