### ISSUE TITLE
No scen_gt.json!!

### ISSUE THREAD

**Issue by VerseWei** [cnhaox/NeRF-HuGS#2]
Nice work!

I run HuGS with Kubric dataset provided by you, but there is an error that no scene_gt.json in data_dir, what's wrong?

FileNotFoundError: [Errno 2] No such file or directory: '/home/***/3D_Recon/NeRF-HuGS/data/kubric_colmap/kubric_car/scene_gt.json'

**Comment by VerseWei** [comment]
@cnhaox hello, could you help me? Thanks!

**Comment by cnhaox** [comment]
> @cnhaox hello, could you help me? Thanks!

@VerseWei Hi there! I assume you have downloaded the Kubric colmap data we provided, but not the [original dataset](https://drive.google.com/drive/folders/1B97cgpv3ivYlUXg6yqIAPRnOa4l1Kcx3). In fact, the latter is the data that nerf needs for training and rendering, while the former is only used for SfM-based heuristics. Therefore, you need to download all the data and set the corresponding path.

**Comment by VerseWei** [comment]
Yes, I find it , thanks! @cnhaox
