### ISSUE TITLE
Is the mask provided in google drive the one produced by using MipNeRF360?

### ISSUE THREAD

**Issue by yt2639** [cnhaox/NeRF-HuGS#3]
Hi thanks for your great work! I am wondering if the mask provided [here](https://drive.google.com/drive/folders/1-6PhBWn_ZhPdUbY_up-d89-Agb5xaGMy) in the google drive is generated by using MipNeRF360 or NeRFacto? More specifically, I am asking in terms of the phototourism dataset.

Thanks a lot!

**Comment by cnhaox** [comment]
> Hi thanks for your great work! I am wondering if the mask provided [here](https://drive.google.com/drive/folders/1-6PhBWn_ZhPdUbY_up-d89-Agb5xaGMy) in the google drive is generated by using MipNeRF360 or NeRFacto? More specifically, I am asking in terms of the phototourism dataset.
> 
> Thanks a lot!

nerfacto
